
cmake_minimum_required(VERSION 3.28 FATAL_ERROR)
set(CMAKE_CXX_SCAN_FOR_MODULES OFF)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
set(CMAKE_COLOR_DIAGNOSTICS ON)
set (PROJECT_VERSION_MAJOR 0)
set (PROJECT_VERSION_MINOR 2)
set (PROJECT_VERSION_REV 1)
set (PROJECT_VERSION ${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_REV})
include (cmake/cmake_init.cmake)
include (cmake/doxygen.cmake)
include (cmake/deploy/deploy_dependencies.cmake)

include (cmake/archflags.cmake)
include (cmake/generators/version_header.cmake)
include (cmake/generators/export_header.cmake)
project(FusedKernelLibrary VERSION ${PROJECT_VERSION} LANGUAGES CXX 
DESCRIPTION "Implementation of a methodology that allows all sorts of user defined GPU kernel fusion, for non CUDA programmers." 
HOMEPAGE_URL "https://github.com/morousg/FusedKernelLibrary" )

#cuda is optional, but if it is found, it will be used
option(ENABLE_CPU "Enable CPU support" ON)
option(ENABLE_CUDA "Enable CUDA support" ON)
option(ENABLE_HIP "Enable HIP support" OFF)

if (ENABLE_CUDA AND ENABLE_HIP)
    message(FATAL_ERROR "ENABLE_CUDA and ENABLE_HIP cannot be enabled at the same time.")
endif()

include(CheckLanguage)

if (ENABLE_CPU)
    check_language(CXX)
    if (CMAKE_CXX_COMPILER)
         enable_language(CXX)
    #    include(cmake/cpu_init.cmake)
    else()
    #    message(FATAL_ERROR "C++ compiler not found. the build cannot proceed.")
    endif()
endif()

if (ENABLE_CUDA)
    check_language(CUDA)
    if (CMAKE_CUDA_COMPILER)
        include(cmake/cuda_init.cmake)
    else()
    if (NOT (ENABLE_CPU))
            message(FATAL_ERROR "CUDA compiler not found. the build cannot proceed.")
        else ()
            message(WARNING "CUDA compiler not found. Disabling CUDA support.")
            set(ENABLE_CUDA OFF CACHE BOOL "Enable CUDA support" FORCE)
        endif()        
        
    endif()
endif()

if (ENABLE_HIP)
    check_language(HIP)
    if(NOT DEFINED HIP_PATH)
        if(NOT DEFINED ENV{HIP_PATH})
            set(HIP_PATH "/opt/rocm/hip" CACHE PATH "Path to which HIP has been installed")
                   message(STATUS "HIP_PATH: " ${HIP_PATH})
        else()
            set(HIP_PATH $ENV{HIP_PATH} CACHE PATH "Path to which HIP has been installed")
            message(STATUS "HIP_PATH: " ${HIP_PATH})
        endif()
    endif()
    #set(CMAKE_MODULE_PATH "${HIP_PATH}/cmake" ${CMAKE_MODULE_PATH})

    if (NOT DEFINED ROCM_PATH )
        set ( ROCM_PATH "/opt/rocm"  CACHE STRING "Default ROCM installation directory." )
    else()
        set ( ROCM_PATH $ENV{ROCM_PATH}  CACHE STRING "Default ROCM installation directory." )
    endif ()

    # Search for rocm in common locations
    list(APPEND CMAKE_PREFIX_PATH ${HIP_PATH}/cmake ${HIP_PATH}/cmake/hip-lang ${ROCM_PATH})
    message(STATUS "CMAKE_PREFIX_PATH: " ${CMAKE_PREFIX_PATH})
    find_package(hip-lang CONFIG REQUIRED)
    message(STATUS "Found hip-lang")
    if (CMAKE_HIP_COMPILER)       
        message("Using HIP compiler at " ${CMAKE_HIP_COMPILER})    
        set(CMAKE_CXX_SCAN_FOR_MODULES OFF) #clang with HIP does not come with  clang-scan-deps
        include(cmake/hip_init.cmake)    
    else()
        if (NOT (ENABLE_CPU))
            message(FATAL_ERROR "HIP compiler not found. the build cannot proceed. ")        
        else ()
            message(WARNING "HIP compiler not found. Disabling HIP support.")
            set(ENABLE_HIP OFF CACHE BOOL "Enable HIP support" FORCE)
        endif()        
    endif()
endif()

add_subdirectory(include)
add_subdirectory(lib)

option (BUILD_TEST "build standard  tests" ON)
option (BUILD_UTEST "build standard unit tests" ON)
option (ENABLE_BENCHMARK "build benchmarking unit tests" OFF)

if (${BUILD_TEST})    
    include (cmake/tests/discover_tests.cmake)
    enable_testing()  
    add_subdirectory(tests)    
endif()

if (${BUILD_UTEST})    
    include (cmake/tests/discover_tests.cmake)
    enable_testing()      
    add_subdirectory(utests)         
endif()

if (${ENABLE_BENCHMARK})
    include (cmake/tests/discover_tests.cmake)
    enable_testing()
    add_subdirectory(benchmarks)
endif()
