name: CMake on Windows (x64)

on:
  #push:
  #  branches: [ $default-branch ]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: [self-hosted, windows, x64, rocm]

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false
      matrix:        
        include:
          - msvc_env_version: "14.44"  #HIP on windows is vs2022 only
            rocm_version: "7.2"
 

    steps:
      - uses: actions/checkout@v6

      - name: Set reusable strings
        # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
        id: strings
        run: |
          echo "build-output-dir=${{github.workspace}}/build" >> "$env:GITHUB_OUTPUT"                     
          echo "CC=$env:HIP_PATH\bin\clang.exe" >> "$env:GITHUB_ENV"
          echo "CXX=$env:HIP_PATH\bin\clang++.exe" >> "$env:GITHUB_ENV"
          echo "HIPCXX=$env:HIP_PATH\bin\clang++.exe"  >> "$env:GITHUB_ENV"
          echo "CMAKE_PREFIX_PATH=$env:HIP_PATH" >> "$env:GITHUB_ENV"

      - name: Detect visual studio installation (2022)
        run: |
          $vsWhere = "${Env:ProgramFiles(x86)}/Microsoft Visual Studio/Installer/vswhere.exe"   
          $vsInstallationPath = & $vsWhere -products * -version "[17.0,18.0)" -property installationPath        
          echo "VS_INSTALLATION_PATH=$vsInstallationPath" >> "$env:GITHUB_ENV"
          echo "DEV_ARGS=-arch=x64 -vcvars_ver=${{matrix.msvc_env_version}}" >> "$env:GITHUB_ENV"

      - name: Configure CMake
        run: |
          Import-Module (Get-ChildItem $env:VS_INSTALLATION_PATH -Recurse -File -Filter Microsoft.VisualStudio.DevShell.dll).FullName           
          Enter-VsDevShell -VsInstallPath  $env:VS_INSTALLATION_PATH  -SkipAutomaticLocation -DevCmdArguments $env:DEV_ARGS             
          cmake -G "Ninja" -DENABLE_HIP=ON -DENABLE_CUDA=OFF `
          -DCMAKE_HIP_ARCHITECTURES="gfx1200" -B ${{steps.strings.outputs.build-output-dir}} -DCMAKE_BUILD_TYPE=Release -S ${{github.workspace}};        
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }          
          

      - name: Build        
        run: |
          Import-Module (Get-ChildItem $env:VS_INSTALLATION_PATH -Recurse -File -Filter Microsoft.VisualStudio.DevShell.dll).FullName           
          Enter-VsDevShell -VsInstallPath $env:VS_INSTALLATION_PATH -SkipAutomaticLocation -DevCmdArguments $env:DEV_ARGS                 
          cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Release

      - name: Test
        working-directory: ${{ steps.strings.outputs.build-output-dir }}               
        run: ctest --build-config Release --output-junit test_results.xml
